### ISSUE TITLE
Can't bookmark/refresh download page in DataObject

### ISSUE THREAD

**Issue by robingram** [silverstripe/silverstripe-gridfieldqueuedexport#21]
Bookmarking or refreshing the download page works at the Model Admin level but if I have the queued export button on a GridField for a `has_many` relationship on a data object then refreshing the page doesn't work. I get a blank page except for the string `ViewableData_Customised`.

**Comment by robbieaverill** [comment]
Are you able to fish out any error logs?

**Comment by robingram** [comment]
Nothing in Apache or PHP error logs, or if I add logging in my `_config.php`. Since it isn't actually outputting an error message I'm not sure that it is resulting in an uncaught exception. Looks more like it is rendering the wrong thing.

**Comment by robingram** [comment]
The problem centres on the behaviour when the request isn't AJAX:

```
if ($request->isAjax()) {
    return $return;
} else {
    return $controller->customise(array('Content' => $return));
}
```

**Comment by robbieaverill** [comment]
Hey @robingram, when you get a chance could you try and provide a bit more context around this?

I've tested this on CWP 1.5 and CWP 1.7 (SS 3.5 an 3.6) with gridfieldqueuedexport 1.1.x using the following configuration:

```php
class Page extends BasePage
{
	private static $has_many = array(
		'Monkeys' => 'Monkey'
	);

	public function getCMSFields()
	{
		$fields = parent::getCMSFields();

		$fields->addFieldToTab(
			'Root.Main',
			$gridField = GridField::create('Monkeys', null, $this->Monkeys(), new GridFieldConfig_RecordEditor)
		);

		$config = $gridField->getConfig();
		$config->addComponent($newExportButton = new GridFieldQueuedExportButton());

		return $fields;
	}
}

class Monkey extends DataObject
{
	private static $db = ['Name' => 'Varchar'];

	private static $has_one = [
		'Page' => 'Page'
	];
}
```

My export URL is refreshable, and contains the page ID. 

Are you possibly using an older version of the CMS/framework? In the past page IDs were not stored in the URL, which could cause this sort of behaviour when not posted to or stored in a session.

**Comment by robingram** [comment]
I'm not sure it would be evident with that configuration @robbieaverill. We see the issue in this situation:

- We have Model A with a model admin. The export works and can be refreshed when exporting Model A at the model admin level.
- Model A has a `has_many` relationship to Model B.
- When we edit an instance of Model A we have a gridfield in a separate tab showing the related Model B instances.
- If this Model B gridfield has the queued export button then the export will work but we won't be able to refresh the export page.

Does that make sense?

We're on CWP 1.6 so we're using whatever framework version goes with that.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
