### ISSUE TITLE
None of the following templates could be found (namespace issue)

### ISSUE THREAD

**Issue by alex-candler** [silverstripe/silverstripe-gridfieldqueuedexport#29]
Hi there,
I am running silverstripe-gridfieldqueuedexport 2.1, SilverStripe 4.2 & PHP 7.1.22 and I came across a namespacing issue where the template for GridFieldQueuedExportButton cannot be found after clicking the export button. 
`None of the following templates could be found: SilverStripe\GridfieldQueuedExport\Forms\GridFieldQueuedExportButton in themes "Array ( [0] => silverstripe/admin:cms-forms [1] => $default ) " 
SSViewer.php:215`
<img width="848" alt="template could not be found when exporting csv" src="https://user-images.githubusercontent.com/5172852/46442522-6662c080-c7c6-11e8-98e4-303f6c882e4c.png">

Although the template file is actually located under `templates/SilverStripe/GridFieldQueuedExport/Forms/GridFieldQueuedExportButton.ss` (note the difference of `GridField` vs `Gridfield`.

Looks like the namespacing needs to be updated to match `GridField` or I just changed the folder for the template to `templates/SilverStripe/GridfieldQueuedExport/Forms/GridFieldQueuedExportButton.ss` for the meantime.

Cheers,
Alex

**Comment by robbieaverill** [comment]
PR at #30
