### ISSUE TITLE
Investigate: Multi server "export has already been downloaded"

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-gridfieldqueuedexport#32]
On multi server environments sometime the error message "This export has already been downloaded. For security reasons each export can only be downloaded once." appears

This is because the queued job has completed, and the file is on one server, but not the server you are currently on, so the GridFieldQueuedExportButton.php  file_exists() check will fail

The file will sync across, and refreshing the CMS will fix this, however this isn't obvious to the user

## Pull requests

- [x] SS3: https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/33
- [x] SS4: https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/34
- [x] CWP 1.x: https://github.com/silverstripe/cwp/pull/167
- [x] CWP 2.x: https://github.com/silverstripe/cwp/pull/168

**Comment by NightJar** [comment]
@emteknetnz can you please provide version information with this?
What version of SS, this module, etc.

**Comment by emteknetnz** [comment]
1.0.x-dev
39020c844255ac4047e846030ab9ea20152188f7
CWP 1.9.0
SS 3.7.1

**Comment by NightJar** [comment]
Thanks, I'll assume that this remains an issue with SS4 too :)

**Comment by brettt89** [comment]
If the export is being written to `assets/` directory, these are normally synchronized between all servers, so the file should exist on all servers.

**Comment by NightJar** [comment]
Yeah, but how long until that happens? I don't imagine it's immediate in most cases @brettt89 - in @emteknetnz's case I presume after the download link is presented,  **and** the user clicks it.

**Comment by emteknetnz** [comment]
Export Path is

return ASSETS_PATH."/.exports/$id/$id.csv";

where $id is a hash like 123abcde285327fd67f1c540c5dfc24b

**Comment by brynwhyman** [comment]
Spiking this for now to investigate. 3 points

**Comment by NightJar** [comment]
Thoughts to discuss with server folks at a later point:
 * Lock the request for `.exports/*` to a specific server - how to capture which? How long to persist?
 * Is there a way to tell if sync has happened? Make export task wait for it.
 * Poll some endpoint to see which server (or all) a file is available at?
 * Have 404's search other servers too?
 * Add a notice to let a user know to try again if their file isn't available. How to know when it shouldn't be available?

**Comment by emteknetnz** [comment]
GridFieldQueuedExportButton.php
```
        if ($job->JobStatus == QueuedJob::STATUS_COMPLETE) {
            if (file_exists($this->getExportPath($id))) {
```

could change this to 

```
        if ($job->JobStatus == QueuedJob::STATUS_COMPLETE && $job->JobFinished [at least 30 seconds ago]) {
            if (file_exists($this->getExportPath($id))) {
```

that should achieve much the same as option 1?

**Comment by ScopeyNZ** [comment]
Seems a bit hacky but if you make the `[at least 30 seconds ago]` configurable and default to the common use case (no delay) then I'd be happy to accept that PR.

**Comment by NightJar** [comment]
`sleep($sleepDuration);` would be better placed in the job, before it finishes(`STATUS_COMPLETE`).

**Comment by robbieaverill** [comment]
Cool, sounds like we're roughly on board with "fixing" this by using option 1 from above:

>1: Build in a configurable sleep time at the end of the generation task, which can be used to compensate for NFS synchronisation delays (or similar)

**Comment by robbieaverill** [comment]
I've skeptically added the v3 label back again, we can patch it in both branches

**Comment by robbieaverill** [comment]
All PRs posted to the issue description - I've gone with an arbitrary 15 second configuration (in CWP config) which hopefully will be a middle ground between avoiding the asset sync issue and not pissing the CMS users off too much.

**Comment by NightJar** [comment]
All PRs merged.
