### ISSUE TITLE
Nested gridfield compatibility seems broken

### ISSUE THREAD

**Issue by dizzystuff** [silverstripe/silverstripe-gridfieldqueuedexport#55]
I think this may be an issue with nested grid fields.

Upon clicking the queued export button, the page reloads, and simply displays the string `SilverStripe\View\ViewableData_Customised`

This is occurring on ElementForm submission exports, and any other gridfield I've tried it on within elemental Elements.

**Comment by ishannz** [comment]
@emteknetnz this will fix in https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/61
