### ISSUE TITLE
PermissionFailure for user after clicking export button

### ISSUE THREAD

**Issue by baukezwaan** [silverstripe/silverstripe-gridfieldqueuedexport#58]
On a particular environment we encountered a permission-issue after a server-update. The permission is checked in the GridField_URLHandler to make sure the right user is accessing the export.

/src/Forms/GridFieldQueuedExporButton.php
```
    public function checkExport($gridField, $request = null)
    {
        $id = $request->param('ID');
        $job = QueuedJobDescriptor::get()->filter('Signature', $id)->first();

        
        if ((int)$job->RunAsID !== Security::getCurrentUser()->ID) {
            return Security::permissionFailure();
        }
```

The problem seems to be that the Security::getCurrentUser()->ID is returned as a sting, and the $job->RunAsID is casted into an INT.

Can I make a PR to change this into 

```
        if ((int)$job->RunAsID !== (int)Security::getCurrentUser()->ID) {
```

Or is there some other voodoo going on, why my CurrentUser is returning a string?

silverstripe/framework: 4.8.0
silverstripe/gridfieldqueuedexport: 2.3.0

**Comment by emteknetnz** [comment]
That seems pretty odd, it should be an int, it seems like an edge case. Without spending too much time going down a rabbit hole trying to work out why this is happening, I see no harm in casting it to (int) - feel free to raise this as a PR to the next-patch branch (currently `2.5`)

**Comment by emteknetnz** [comment]
Merged PR - https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/60
