### ISSUE TITLE
info message when after running filling up the logs

### ISSUE THREAD

**Issue by vinstah** [silverstripe/silverstripe-gridfieldqueuedexport#85]
This message displays continuously after running the task 
error-log.INFO: Next pending job could NOT be found or lock could NOT be obtained. [] []

exporting UDF submissions

GFQE version 2.8.1

**Comment by NightJar** [comment]
This comes from [`symbiote/silverstripe-queuedjobs`](https://github.com/symbiote/silverstripe-queuedjobs), not GFQE :)

It comes from using Doorman runner when the process manager tick is true, but there is no descriptor.

It's an `info` message letting you know there's no next job.

You can set a different logger on `QueuedJobService` via `Injector` that has handlers set to a higher threshold than `INFO` to quiet it.

**Comment by GuySartorelli** [comment]
It sounds like at a minimum, this is on the wrong repository. I'm closing this issue.
If the information NightJar provided isn't enough to resolve this for you @vinstah please open a new issue in the appropriate repository.
